name: Build and publish library to GitHub registry

on:
  release:
    types: [created]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: Setup NPM
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build-lib
      - name: Pack
        working-directory: ./dist/ngx-signature-pads
        run: npm pack
      - name: Publish To Github
        working-directory: ./dist/ngx-signature-pads
        run: |
          cd dist/${{ github.event.inputs.project_name }}
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
