name: Build and publish library to NPM registry

on:
  release:
    types: [created]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: Setup NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm i
      - name: Build lib
        run: npm run build-lib
      - name: Configure npm registry for NPM js Packages
        run: npm config set registry https://registry.npmjs.org/
      - name: Publish To Github
        run: |
          cd dist/ngx-signature-pads
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
