name: Build and publish library to npm.js registry

on:
  release:
    types: [created]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: Setup NPM
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build-lib
      - name: Pack
        working-directory: ./dist/ngx-signature-pads
        run: npm pack
      - name: Publish
        working-directory: ./dist/ngx-signature-pads
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          token: ${{secrets.NPM_TOKEN}}
